apiVersion: apps/v1
kind: Deployment
metadata:
  name: sourabh-assessment
  labels:
    app: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment
  template:
    metadata:
      labels:
        app: assessment
    spec:
      containers:
      - name: assessment
        image: 12sourabh/assessment:0.1
        ports:
          - containerPort: 5000